default_configuration:
  model_type: 'yolov8m'
  seed: 42 # Seed for reproducibility
  model_directory: 'models' # Directory to save the model
  load_saved_model: False # Load saved models from the model directory instead of training
  data_split: 
    train_split: 0.5 # Train split
    validation_split: 0.3 # Validation split
    test_split: 0.2 # Test split
  training_parameters: # 
    epochs: 10
    device: "cpu" # Device to run the model on. cpu is standard for most, mps available for Apple Silicon with Metal Performance Shaders (MPS). Select 0 or 1 for GPU 
    batch: 64 # Batch size 
    imgsz: 320 # Image size (width and height) for training
    cache: 'ram' # Cache images for faster training. Options: 'ram' or 'disk'. 'ram' is faster but uses more memory. 'disk' is slower but uses less memory. 'ram' is not deterministic.
    resume: False # Resume training from a previous run
    time: 2 # Max time for training, in hours
  doc: Note that anything that is not specified in the individual model will be taken from here. Almost all parameters from here can be overridden in the individual model configuration.
model_metadata: 
  model1: 
    model_type: 'yolov8m'
    training_parameters: 
      epochs: 50